### ISSUE TITLE
ChartJs2 Y labels with small datasets

### ISSUE THREAD

**Issue by jmiller656** [RITAccess/Glance-data-analyzer#171]
In the ChartJs2 branch, if you make a new table with a small dataset (ex. 1 row, 2 columns), there is a problem. If you change the first column to 2 and the second column to 4, it will cause the highest y-value to be slightly less than the highest point (3.8 instead of 4 in this case). 
![errorjpg](https://cloud.githubusercontent.com/assets/8846806/13153772/b0771670-d643-11e5-80f7-a676befaff8d.jpg)

**Comment by Outofit08** [comment]
this problem is fixed. The y-values are integers instead of doubles and no longer show numerical tenth place values. The chart will now jump to 5 if you put in 4.3 instead of 4 in the above example. 
this bug is closed. 
<img width="913" alt="screen shot 2017-02-20 at 1 36 04 pm" src="https://cloud.githubusercontent.com/assets/21371701/23139346/95b7e58a-f771-11e6-9d5b-8a0dd81a73a1.png">
